// book actions
export const RECEIVE_BOOK_LIST = 'RECEIVE_BOOK_LIST';
export const REQUEST_BOOK_LIST = 'REQUEST_BOOK_LIST';
export const CHANGE_AUTHOR_ID = 'CHANGE_AUTHOR_ID';
export const CHANGE_GENRE_ID = 'CHANGE_AUTHOR_ID';
export const ERROR_BOOK_LIST = 'REQUEST_BOOK_LIST';
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
export const SHOW_DELETE_MODAL = 'SHOW_DELETE_MODAL';
export const SHOW_NOTIFICATION_POP_UP = 'SHOW_NOTIFICATION_POP_UP';

// author actions
export const RECEIVE_AUTHOR_LIST = 'RECEIVE_AUTHOR_LIST';
export const REQUEST_AUTHOR_LIST = 'REQUEST_AUTHOR_LIST';
export const ERROR_AUTHOR_LIST = 'ERROR_AUTHOR_LIST';

// genre actions
export const RECEIVE_GENRE_LIST = 'RECEIVE_GENRE_LIST';
export const REQUEST_GENRE_LIST = 'REQUEST_GENRE_LIST';
export const ERROR_GENRE_LIST = 'ERROR_GENRE_LIST';